### ISSUE TITLE
Can't find utility_templates in shiji 1.0.14 from Pypi.

### ISSUE THREAD

**Issue by JudgeGregg** [williamsjj/shiji#1]
It seems the utility_templates directory is missing in the 1.0.14 package on Pypi, which results in shiji_admin failing with:

```
$ shiji_admin -A testapi -V 1.0

Traceback (most recent call last):
  File "/home/greg/.virtualenvs/Shiji/bin/shiji_admin", line 9, in <module>
    load_entry_point('shiji==1.0.14', 'console_scripts', 'shiji_admin')()
  File "/home/greg/.virtualenvs/Shiji/local/lib/python2.7/site-packages/shiji/utilities/shiji_admin.py", line 288, in main
    cmd_new(args.api, args.version)
  File "/home/greg/.virtualenvs/Shiji/local/lib/python2.7/site-packages/shiji/utilities/shiji_admin.py", line 100, in cmd_new
    tmpl_new_api = template_lookup.get_template("new_api.py.mako")
  File "/home/greg/.virtualenvs/Shiji/local/lib/python2.7/site-packages/mako/lookup.py", line 259, in get_template
    "Cant locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'new_api.py.mako'
```

Adding the directory from Github solves the issue.

**Comment by heluca** [comment]
Pip install of Shiji will fail on Windows if lxml is not already installed.  Installing lxml from the wheel file from here works fine and Shiji installs successfully: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

**Comment by williamsjj** [comment]
Hi @JudgeGregg. Not sure why I didn't see this when it was opened. Looking into it. The setup.py looks like it's correctly including `utilities/utility_templates/*`

**Comment by williamsjj** [comment]
@heluca Could you please open that as a separate issue? That would appear to me to be a pip issue, since we do specify the lxml dependency properly.

**Comment by williamsjj** [comment]
@JudgeGregg Seems like PIP changed the handling of include_package_data. Removing it fixes the issue. There's a new version in PyPI (1.0.15) that should work for you. Sorry for the issue. Thanks for reporting.
